name: build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        id: golang-with-cache
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: |
          go get .

      - name: Build Go App
        run: make build-go

      - name: Test
        run: make coverage

      - name: Save Golang cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ steps.golang-with-cache.outputs.build-cache-path }}
            ${{ steps.golang-with-cache.outputs.module-cache-path }}
          key: ${{ steps.golang-with-cache.outputs.cache-key }}